# Generated by Django 3.2.12 on 2022-04-05 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLITED', 'Completed'), ('FAILED', 'Failed'), ('NOT_STARTED', 'Not started')], default='NOT_STARTED', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', '1'), ('MEDIUM', '2'), ('HIGH', '3')], default='LOW', max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField(null=True)),
                ('close_date', models.DateTimeField(null=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
