# Generated by Django 3.2.12 on 2022-04-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20220405_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('1', 'LOW'), ('2', 'MEDIUM'), ('3', 'HIGH')], default='LOW', max_length=15),
        ),
    ]
